archetypedir = "archetypes"
baseurl = "https://www.innovationlogistique.com/"
buildDrafts = false
buildFuture = false
canonifyurls = true
# Pointing to this file
config = "config.toml"
contentdir = "content"
copyright = ""

# Create an array of files you don't want hugo to build
ignoreFiles = []
defaultContentLanguage = "fr"
languageCode = "en-us"
# Point the generator to the folder used for layouts and templating
layoutDir = "layouts"
# Enable Logging
log = true
# Log Filepath (if set, logging enabled automatically)
logFil = ""
# This accepts yaml, toml, or json
metaDataFormat = "yaml"
# This intelligently adds an "s" to the titles of list pages
pluralizelisttitles = false
preserveTaxonomyNames = true
# This sets the title of the directory where hugo builds and pushes the final site when running "Hugo" (ie, without "server")
publishdir = "public"
pygmentsUseClasses = true
# relativeURLs = true
source = ""
# This is the top-level, global site title
title = "IILQ"
# Change this once you've created your theme
theme = "iilq"
# Set to true to convert mysite/section/ to mysite/section.html
uglyURLs = false
verbose = false
verboseLog = false
# Setting this to false will keep hugo from watching for changes during local development
watch = true

[permalinks]
  singles = "/:slug/"

#CUSTOM PARAMS
[params]
  sitesubtitle = ""
  organizationname = ""
  copyrightline = ""
  sitedescription = ""
  # Add GA Tracking Code Here. This leverages a built-in (ie, "internal") partial from HUGO: https://gohugo.io/extras/analytics#configuring-google-analytics
  googleanalyticstrackingcode = ""
  ## Critical Render Path. If true, site style will be embedded in a <style> tag in each html <head> as part of Gulp Build. False puts a typical <link> to the stylesheet in <head>>
  usecrp = false
  ## Include jQuery 2.2.4 in your site head. (see /static/assets/js)
  includejq = true
  ## Date the Site is Published, use YYYY-MM-DD
  sitepublishdate = ""
  ## Twitter handle without the "@"
  twitterhandle = ""
  ## Facebook full URL
  facebookurl = ""
  ## LinkedIn full URL
  linkedinurl = ""
  ## YouTube full URL
  youtubeurl = ""
  ## Default Image for Social Sharing. This image should live at static/images/
  defaultsocialimage = ""
  ## Setting this to true will add a "noindex" to *every* page on the site
  removefromexternalsearch = true
  ## This is used when the BaseURL does not need to modified (eg, in share links)
  siteaddress = "https://www.innovationlogistique.com/"
  ## Set to true to add Google Tag Manager to the Site
  addgtm = false
  GTMID = ""
  # Set to true to include a CDN call to FontAwesome
  usefontawesome = false
# MARKDOWN
## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
	plainIDAnchors = true
	hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true

[taxonomies]
  tag = "tags"
  category = "categories"