archetypedir = "archetypes"
baseurl = "https://iilq.netlify.com/"
buildDrafts = false
buildFuture = false
canonifyurls = true
# Pointing to this file
config = "config.toml"
contentdir = "content"
copyright = ""
# This is the top-level, global site title
title = "IILQ | Institut d'Innovation en Logistique du Québec"
# Change this once you've created your theme
theme = "iilq"

# Create an array of files you don't want hugo to build
ignoreFiles = []
defaultContentLanguage = "fr"
languageCode = "en-us"
# Point the generator to the folder used for layouts and templating
layoutDir = "layouts"
# Enable Logging
log = true
# This accepts yaml, toml, or json
metaDataFormat = "yaml"
# This intelligently adds an "s" to the titles of list pages
pluralizelisttitles = false
preserveTaxonomyNames = true
# This sets the title of the directory where hugo builds and pushes the final site when running "Hugo" (ie, without "server")
publishdir = "public"

# Set to true to convert mysite/section/ to mysite/section.html
uglyURLs = false
verbose = false
verboseLog = false
# Setting this to false will keep hugo from watching for changes during local development
watch = true

[permalinks]
  singles = "/:slug/"

#CUSTOM PARAMS
#CUSTOM PARAMS
[params]
  ## Include google maps, with API Key
  googleapikey = ""
  ## This is used when the BaseURL does not need to modified (eg, in share links)
  siteaddress = "https://www.innovationlogistique.com/"
  siteaddressno = "https://www.innovationlogistique.com"
  ## FB share info
  fbpagename = ""
  fbappid = ""
  ## Business name in Schema.org
  schemabiz = "IILQ | Institut d'Innovation en Logistique du Québec"
  ## Google Tag Manager tracking ID
  gtmid = ""

# MARKDOWN
## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
	plainIDAnchors = true
	hrefTargetBlank = true
  angledQuotes = false
  latexDashes = true

[taxonomies]
  tag = "tags"
  category = "categories"