# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "IILQ"
#license = "MIT"
#licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = "Private theme for IILQ website"
homepage = "https://www.innovationlogistique.com/"
#tags = ["", ""]
#features = ["", ""]
min_version = 0.24

[author]
  name = "Félix DeBlois-Beaucage"
  homepage = "akiamarketing.ca"

# If porting an existing theme
[original]
  name = "Ryan Watters"
  homepage = "ryanwatters.io"
  repo = "https://github.com/rdwatters/theme-starter-hugo"
