backend:
  name: github
  repo: felixdb/localc # Path to your Github repository
  branch: master # Branch to update (master by default)

media_folder: "themes/iilq/source-images" # Folder where user uploaded files should go
public_folder: "assets/images" # The src attribute for uploaded media will begin with img/uploads

publish_mode: editorial_workflow

collections:
  - name: "settings"
    label: "Paramètres"
    editor:
      preview: false
    files:
      - name: "coordonnees"
        label: "Coordonnées"
        file: "themes/iilq/data/coordonnees.yml"
        description: "C'est ici que vous pourrez modifier vos coordonnées."
        fields:
          - name: coordonnees
            label: Coordonnées
            widget: object
            create: false
            fields:
              - {label: "Français", name: "fr", widget: "object"}
              - {label: "Anglais", name: "en", widget: "object"}
              - {label: "Numéro de téléphone", name: "phone", widget: "string"}
              - {label: "Téléphone condensé", name: "", widget: "string"}
  #     - name: "equipe"
  #       label: "Membres de l'équipe"
  #       file: "data/equipe.yml"
  #       description: "Votre équipe, ne pas mettre d'accent dans les noms de fichier svp!"
  #       fields:
  #         - name: equipe
  #           label: Membre
  #           widget: list
  #           create: true 
  #           fields:
  #             - {label: "Nom", name: "name", widget: "string"}
  #             - {label: "Fonction en français", name: "fonction", widget: "string"}
  #             - {label: "Fonction en anglais", name: "position", widget: "string"}
  #             - {label: "Ordre", name: "weight", widget: "number"}
  #             - {label: "Image", name: "photo", widget: "image"}
  #     - name: "temoignage"
  #       label: "Témoignages"
  #       file: "data/temoignages.yml"
  #       fields:
  #         - name: orthesepro
  #           label: "Orthèses - Professionels"
  #           widget: object
  #           fields:
  #             - {label: "Témoignages - FR", name: "temoignagefr", widget: "text"}
  #             - {label: "Témoignages - EN", name: "temoignageen", widget: "text"}
  #             - {label: "Témoin - FR", name: "temoinfr", widget: "string"}
  #             - {label: "Témoin - EN", name: "temoinen", widget: "string"}
  #             - {label: "Image", name: "image", widget: "image"}
  #         - name: orthesepatients
  #           label: "Orthèses - Patients"
  #           widget: object
  #           fields:
  #             - {label: "Témoignages - FR", name: "temoignagefr", widget: "text"}
  #             - {label: "Témoignages - EN", name: "temoignageen", widget: "text"}
  #             - {label: "Témoin - FR", name: "temoinfr", widget: "string"}
  #             - {label: "Témoin - EN", name: "temoinen", widget: "string"}
  #             - {label: "Image", name: "image", widget: "image"}
  #         - name: cryovizionpro
  #           label: "Cryovizion - Professionels"
  #           widget: object
  #           fields:
  #             - {label: "Témoignages - FR", name: "temoignagefr", widget: "text"}
  #             - {label: "Témoignages - EN", name: "temoignageen", widget: "text"}
  #             - {label: "Témoin - FR", name: "temoinfr", widget: "string"}
  #             - {label: "Témoin - EN", name: "temoinen", widget: "string"}
  #             - {label: "Image", name: "image", widget: "image"}
  #         - name: cryovizionpatients
  #           label: "Cryovizion - Patients"
  #           widget: object
  #           fields:
  #             - {label: "Témoignages - FR", name: "temoignagefr", widget: "text"}
  #             - {label: "Témoignages - EN", name: "temoignageen", widget: "text"}
  #             - {label: "Témoin - FR", name: "temoinfr", widget: "string"}
  #             - {label: "Témoin - EN", name: "temoinen", widget: "string"}
  #             - {label: "Image", name: "image", widget: "image"}
      - name: "categoriesorg"
        label: "Organisation des catégories"
        file: "data/categoriesorg.yml"
        fields:
          - name: categories
            label: Catégories
            widget: list
            fields:
              - {label: "Nom", name: "nom", widget: "string"}
              - {label: "Lien", name: "url", widget: "string", required: false}
              - {label: "Nombre d'items", name: "nombre", widget: "number"}
              - {label: "Image", name: "photo", widget: "image", required: false}
              - {label: "Sous-catégories", name: "souscategories", widget: "list", required: false}

  - name: "produitsfr" # Used in routes, e.g. /admin/collections/blog
    label: "Produits-FR" # Used in the UI
    folder: "content/produits" # The path to the folder where the documents are stored
    slug: "{{id}}"
    create: true # Allow users to create new documents in this collection
    filter: 
      field: "i18nlanguage"
      value: "fr"
    fields: # The fields for each document, usually in front matter
      - {label: "Backorder?", name: "draft", widget: "boolean", required: false, default: false}
      - {label: "Nom officiel", name: "title", widget: "string"}
      - {label: "Description SEO", name: "description", widget: "text", , required: false}
      - {label: "Lien", name: "slug", widget: "string", default: "ceci-est-un-example", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test/"]}
      - {label: "Nom d'affichage du créateur", name: "nomcreateur", widget: "string", default: "Local C"}
      - {label: "Délai de livraison", name: "delai", widget: "string", default: "3 à 4 semaines"}
      - {label: "Image principale", name: "image", widget: "image"}
      - label: "Toutes les images (incluant la principale)"
        name: "images"
        widget: "list"
        fields: 
          - {label: "Image", name: "url", widget: "image" }
      - {label: "Identifiant du créateur", name: "createurs", widget: "relation", collection: "createursfr", searchFields: ["id"], valueField: "id"}
      - {label: "Catégories", name: "categories", widget: "list"}
      - label: "Quantité et prix (qui formera le tableau)"
        name: "prix"
        widget: "list"
        fields: 
          - {label: "Quantité", widget: "string", name: "quantite" }
          - {label: "Prix pour cette quantité (sans symbole)", widget: "number", name: "montant" }
      - {label: "Note à propos du prix", name: "noteprix", widget: "string", required: false}
      - {label: "Interval de prix (pour l'affichage en catalogue)", name: "pricerange", widget: "string", default: "12,50$ à 17,50$"}
      - label: "Variantes (options pour le client)"
        name: "variante"
        widget: "list"
        required: false
        fields: 
          - {label: "Nom de la variante", widget: "string", name: "nom" }
          - {label: "Les différents choix pour cette variante", widget: "list", name: "choix" }
      - {label: "Personnalisations possibles", name: "personnalisation", widget: "list"}
      - {label: "Produits connexes (utiliser les identifiants)", name: "crosssell", widget: "list"}
      - {label: "Identifiant UNIQUE", name: "id", default: "01-trousse-confort", pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "Svp utilisez le format 04-exemple-produit"], widget: "relation", collection: "produitsfr", searchFields: ["id"], valueField: "id"}
      - {label: "Langue", name: "i18nlanguage", widget: "hidden", default: "fr"}
      - {label: "Menu", name: "menuposition", widget: "hidden", default: "catalogue"}
      - {label: "Description du produit", name: "body", widget: "markdown"}
      - {label: "Type", name: "type", widget: "hidden", default: "produits"}

  - name: "produitsen" # Used in routes, e.g. /admin/collections/blog
    label: "Produits-EN" # Used in the UI
    folder: "content/produits" # The path to the folder where the documents are stored
    slug: "{{id}}.{{i18nlanguage}}"
    create: true # Allow users to create new documents in this collection
    filter: 
      field: "i18nlanguage"
      value: "en"
    fields: # The fields for each document, usually in front matter
      - {label: "Backorder?", name: "draft", widget: "boolean", required: false, default: false}
      - {label: "Nom officiel", name: "title", widget: "string"}
      - {label: "Description SEO", name: "description", widget: "text", , required: false}
      - {label: "Lien", name: "slug", widget: "string", default: "ceci-est-un-example", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test/"]}
      - {label: "Nom d'affichage du créateur", name: "nomcreateur", widget: "string", default: "Local C"}
      - {label: "Délai de livraison", name: "delai", widget: "string", default: "3 à 4 semaines"}
      - {label: "Image principale", name: "image", widget: "image"}
      - label: "Toutes les images (incluant la principale)"
        name: "images"
        widget: "list"
        fields: 
          - {label: "Image", name: "url", widget: "image" }
      - {label: "Identifiant du créateur", name: "createurs", widget: "relation", collection: "createursen", searchFields: ["id"], valueField: "id"}
      - {label: "Catégories", name: "categories", widget: "list"}
      - label: "Quantité et prix (qui formera le tableau)"
        name: "prix"
        widget: "list"
        fields: 
          - {label: "Quantité", widget: "string", name: "quantite" }
          - {label: "Prix pour cette quantité (sans symbole)", widget: "number", name: "montant" }
      - {label: "Note à propos du prix", name: "noteprix", widget: "string", required: false}
      - {label: "Interval de prix (pour l'affichage en catalogue)", name: "pricerange", widget: "string", default: "12,50$ à 17,50$"}
      - label: "Variantes (options pour le client)"
        name: "variante"
        widget: "list"
        required: false
        fields: 
          - {label: "Nom de la variante", widget: "string", name: "nom" }
          - {label: "Les différents choix pour cette variante", widget: "list", name: "choix" }
      - {label: "Personnalisations possibles", name: "personnalisation", widget: "list"}
      - {label: "Produits connexes (utiliser les identifiants)", name: "crosssell", widget: "list"}
      - {label: "Identifiant UNIQUE", name: "id", default: "01-trousse-confort", pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "Svp utilisez le format 04-exemple-produit"], widget: "relation", collection: "produitsfr", searchFields: ["id"], valueField: "id"}
      - {label: "Langue", name: "i18nlanguage", widget: "hidden", default: "en"}
      - {label: "Menu", name: "menuposition", widget: "hidden", default: "catalogue"}
      - {label: "Description du produit", name: "body", widget: "markdown"}
      - {label: "Type", name: "type", widget: "hidden", default: "produits"}
  
  - name: "createursfr" # Used in routes, e.g. /admin/collections/blog
    label: "Créateurs-FR" # Used in the UI
    folder: "content/createurs" # The path to the folder where the documents are stored
    slug: "{{id}}"
    create: true # Allow users to create new documents in this collection
    filter: 
      field: "i18nlanguage"
      value: "fr"
    fields: # The fields for each document, usually in front matter
      - {label: "Rendre invisible?", name: "draft", widget: "boolean", required: false, default: false}
      - {label: "Type", name: "type", widget: "hidden", default: "createursindiv"}
      - {label: "Nom officiel", name: "title", widget: "string"}
      - {label: "Description SEO", name: "description", widget: "text", , required: false}
      - {label: "Identifiant UNIQUE", name: "id", default: "localc", pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "Svp utilisez le format 04-exemple-article"], widget: "relation", collection: "createursfr", searchFields: ["id"], valueField: "id"}
      - {label: "Lien (identique à l'identifiant)", name: "slug", widget: "string", default: "localc", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test/"]}
      - {label: "Site web du créateur (OBLIGATOIRE)", name: "site", widget: "string"}
      - {label: "Lien vers sa page Facebook", name: "facebook", widget: "string", required: false}
      - {label: "Lien vers sa page Instagram", name: "instagram", widget: "string", required: false}
      - {label: "Lien vers sa page Pinterest", name: "pinterest", widget: "string", required: false}
      - {label: "Lien vers sa page LinkedIn", name: "linkedin", widget: "string", required: false}
      - {label: "Image ", name: "image", widget: "image"}
      - {label: "Langue", name: "i18nlanguage", widget: "hidden", default: "fr"}
      - {label: "Menu", name: "menuposition", widget: "hidden", default: "createurs"}
      - {label: "Description du créateur", name: "body", widget: "markdown"}

  - name: "createursen" # Used in routes, e.g. /admin/collections/blog
    label: "Créateurs-EN" # Used in the UI
    folder: "content/createurs" # The path to the folder where the documents are stored
    slug: "{{id}}.{{i18nlanguage}}"
    create: true # Allow users to create new documents in this collection
    filter: 
      field: "i18nlanguage"
      value: "en"
    fields: # The fields for each document, usually in front matter
      - {label: "Rendre invisible?", name: "draft", widget: "boolean", required: false, default: false}
      - {label: "Type", name: "type", widget: "hidden", default: "createursindiv"}
      - {label: "Nom officiel", name: "title", widget: "string"}
      - {label: "Description SEO", name: "description", widget: "text", , required: false}
      - {label: "Identifiant UNIQUE", name: "id", default: "localc", pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "Svp utilisez le format 04-exemple-article"], widget: "relation", collection: "createursfr", searchFields: ["id"], valueField: "id"}
      - {label: "Lien (identique à l'identifiant)", name: "slug", widget: "string", default: "localc", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test/"]}
      - {label: "Site web du créateur (OBLIGATOIRE)", name: "site", widget: "string"}
      - {label: "Lien vers sa page Facebook", name: "facebook", widget: "string", required: false}
      - {label: "Lien vers sa page Instagram", name: "instagram", widget: "string", required: false}
      - {label: "Lien vers sa page Pinterest", name: "pinterest", widget: "string", required: false}
      - {label: "Lien vers sa page LinkedIn", name: "linkedin", widget: "string", required: false}
      - {label: "Image ", name: "image", widget: "image"}
      - {label: "Langue", name: "i18nlanguage", widget: "hidden", default: "en"}
      - {label: "Menu", name: "menuposition", widget: "hidden", default: "createurs"}
      - {label: "Description du créateur", name: "body", widget: "markdown"}
