backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
  branch: master # Branch to update (master by default)

media_folder: "themes/iilq/source-images" # Folder where user uploaded files should go
public_folder: "/img" # The src attribute for uploaded media will begin with

publish_mode: editorial_workflow

collections:
### ARTICLES
  - name: "articles-fr" # Used in routes, e.g. /admin/collections/blog
    label: "Articles - FR" # Used in the UI
    folder: "content/articles" # The path to the folder where the documents are stored
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    editor:
      preview: true
    create: true # Allow users to create new documents in this collection
    filter: 
      field: "i18nlanguage"
      value: "fr"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description SEO", name: "description", widget: "text", required: false}
      - {label: "Lien", name: "slug", widget: "string", default: "this-is-an-example", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test"], hint: "Si le lien désiré est https://www.innovationlogistique.com/articles/les-mecanismes-de-l-algorithme-airbnb, entrez 'les-mecanismes-de-l-algorithme-airbnb' dans ce champ."}
      - {label: "Identifiant Unique", name: "translationKey", widget: "string", default: "this-is-an-example", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test"], hint: "Ce champ doit être unique parmi vos articles."}
      # Si un jour le CMS est bilingue, cette clé permet de trouver l'homonyme anglais de l'article
      # - label: "Identifiant Unique"
      #   name: "translationKey"
      #   pattern: ["^[a-z0-9]+(?:-[a-z0-9]+)*$", "Svp utilisez le format ceci-est-unique"]
      #   widget: "relation"
      #   collection: "articles-en"
      #   searchFields: ["translationKey","title"]
      #   valueField: "translationKey"
      #   displayFields: ["title", "i18nlanguage"]
      #   hint: "Trouvez la traduction de cette page en utilisant cet outil de recherche. Si elle n'existe pas encore, entrez un identifiant unique pour cette page dans le format ceci-est-unique."
      - {label: "Langue", name: "i18nlanguage", widget: "hidden", default: "fr"}
      - {label: "Image", name: "image", widget: "image", hint: "On vise une résolution de 1920px par 1280px."}
      - {label: "Image Carrée", name: "imagecarree", widget: "image", hint: "On vise une résolution de 1920px par 1920px."}
      - {label: "Bannière", name: "banniere", widget: "image", hint: "On vise une résolution de 1920px par 1280px."}
      - {label: "Auteur", name: "author", widget: "string", required: true}
      - {label: "Priority (0 is the most important)", name: "weight", widget: "number", default: 0, required: false}
      - {label: "Date de publication", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Categories (separate with commas)", name: "categories", widget: "list", required: false}
      - {label: "Hide from website?", name: "draft", widget: "boolean", required: false, default: false}
      - {label: "Remove from search engine?", name: "noindex", widget: "boolean", required: false, default: false}
      - {label: "Texte", name: "body", widget: "markdown"}
### CASE STUDIES FR
  - name: "case-studies-fr" # Used in routes, e.g. /admin/collections/blog
    label: "Études de cas - FR" # Used in the UI
    folder: "content/etudes-de-cas" # The path to the folder where the documents are stored
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    editor:
      preview: true
    create: true # Allow users to create new documents in this collection
    filter: 
      field: "i18nlanguage"
      value: "fr"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description SEO", name: "description", widget: "text", required: false}
      - {label: "Lien", name: "slug", widget: "string", default: "this-is-an-example", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test"], hint: "Si le lien désiré est https://www.innovationlogistique.com/articles/les-mecanismes-de-l-algorithme-airbnb, entrez 'les-mecanismes-de-l-algorithme-airbnb' dans ce champ."}
      - {label: "Image de partage", name: "image", widget: "image" , required: false, hint: "La taille recommandée est de 1200px x 630px"}
      - name: general
        label: "Général"
        widget: object
        fields:
          - {label: "Titre", name: "title", widget: "string"}
          - {label: "Description", name: "description", widget: "text"}
          - {label: "Image - Haut de page", name: "img", widget: "image", hint: "La taille recommandée est de 1920px par 930px"}
      - {label: "Priorité sur la page liste (0 est prioritaire)", name: "weight", widget: "number", default: 0, required: false}
      - {label: "Ne pas rendre visible", name: "draft", widget: "boolean", required: false, default: false}
      - {label: "Cacher des moteurs de recherche", name: "noindex", widget: "boolean", required: false, default: false}
      - {label: "Texte", name: "body", widget: "markdown"}
      - {label: "Langue", name: "i18nlanguage", widget: "hidden", default: "fr"}
  - name: "other-pages" # Used in routes, e.g. /admin/collections/blog
    label: "Autres Pages" # Used in the UI
    folder: "content/singles" # The path to the folder where the documents are stored
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "yaml-frontmatter"
    editor:
      preview: true
    create: true # Allow users to create new documents in this collection
    filter: 
      field: "layout"
      value: "other"
    fields:
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Description SEO", name: "description", widget: "text", required: false}
      - {label: "Lien", name: "slug", widget: "string", default: "this-is-an-example", pattern: ["^[a-z0-9]+(?:-[a-z0-9/]+)*$", "Svp utilisez le format ceci-est-un-test"], hint: "Si le lien désiré est https://www.innovationlogistique.com/les-mecanismes-de-l-algorithme-airbnb, entrez 'les-mecanismes-de-l-algorithme-airbnb' dans ce champ."}
      - {label: "Image de partage", name: "image", widget: "image" , required: false, hint: "La taille recommandée est de 1200px x 630px"}
      - name: general
        label: "Général"
        widget: object
        fields:
          - {label: "Image - Haut de page", name: "img", widget: "image", hint: "La taille recommandée est de 1920px par 930px"}
          - {label: "Titre - Haut de page", name: "title", widget: "string"}
      - {label: "Texte", name: "body", widget: "markdown"}
      - {label: "Ne pas rendre visible", name: "draft", widget: "boolean", required: false, default: false}
      - {label: "Cacher des moteurs de recherche", name: "noindex", widget: "boolean", required: false, default: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "other"}
### OTHER
  - name: "pages"
    label: "Pages"
    editor:
      preview: false
    files:
      - name: "accueil"
        label: "Page d'accueil"
        file: "content/_index.md"
        description: "Texte de votre page d'accueil"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text"}
          - {label: "Image de partage", name: "image", widget: "image" , required: false, hint: "La taille recommandée est de 1200px x 630px"}
          - name: slider
            label: Slider - Haut de page
            widget: list
            allow_add: true
            fields:
              - {label: "Texte du haut", name: "toptxt", widget: "string"}
              - {label: "Texte du bas", name: "bottomtxt", widget: "string"}
              - {label: "Image", name: "img", widget: "image" , hint: "La taille recommandée est de 1920px x 930px"}
              - label: "Format" 
                name: "layout"
                widget: "select"
                options:
                  - { label: "Texte gras en haut", value: 1 }
                  - { label: "Texte gras en bas", value: 2 }
              - {label: "Lien", name: "link", widget: "string", hint: "Si vous voulez aller à https://www.innovationlogistique.com/contact, vous devez entrer 'contact'."}
          - { name: introtext, label: Texte d'introduction, widget: markdown }
          - name: section2
            label: "Section - 3 icônes"
            widget: object
            fields:
              - {label: "Colonne 1", name: "title1", widget: "string"}
              - {label: "Colonne 2", name: "title2", widget: "string"}
              - {label: "Colonne 3", name: "title3", widget: "string"}
          - name: boites
            label: "Section - Images, texte et icône"
            widget: object
            fields:
              - name: boite1
                label: "Ligne 1"
                widget: object
                fields:
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Image", name: "img", widget: "image", hint: "Utilisez une image de 1024px par 683px."}
                  - {label: "Lien", name: "link", widget: "string"}
                  - label: "Icône" 
                    name: "icon"
                    widget: "select"
                    options:
                      - { label: "Tête avec ampoule", value: ico-head-light }
                      - { label: "Tableau", value: icon-chart-ico }
                      - { label: "Écran", value: icon-monitor-ico }
                      - { label: "Téléphone intelligent", value: icon-mobile-ico}
                  - {label: "Visible", name: "visible", widget: "boolean", required: false, default: true}
              - name: boite2
                label: "Ligne 2"
                widget: object
                fields:
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Image", name: "img", widget: "image", hint: "Utilisez une image de 1024px par 683px."}
                  - {label: "Lien", name: "link", widget: "string"}
                  - label: "Icône" 
                    name: "icon"
                    widget: "select"
                    options:
                      - { label: "Tête avec ampoule", value: ico-head-light }
                      - { label: "Tableau", value: icon-chart-ico }
                      - { label: "Écran", value: icon-monitor-ico }
                      - { label: "Téléphone intelligent", value: icon-mobile-ico}
                  - {label: "Visible", name: "visible", widget: "boolean", required: false, default: true}
              - name: boite3
                label: "Ligne 3"
                widget: object
                fields:
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Image", name: "img", widget: "image", hint: "Utilisez une image de 1024px par 683px."}
                  - {label: "Lien", name: "link", widget: "string"}
                  - label: "Icône" 
                    name: "icon"
                    widget: "select"
                    options:
                      - { label: "Tête avec ampoule", value: ico-head-light }
                      - { label: "Tableau", value: icon-chart-ico }
                      - { label: "Écran", value: icon-monitor-ico }
                      - { label: "Téléphone intelligent", value: icon-mobile-ico}
                  - {label: "Visible", name: "visible", widget: "boolean", required: false, default: true}
              - name: boite4
                label: "Ligne 4"
                widget: object
                fields:
                  - {label: "Titre", name: "title", widget: "string"}
                  - {label: "Image", name: "img", widget: "image", hint: "Utilisez une image de 1024px par 683px."}
                  - {label: "Lien", name: "link", widget: "string"}
                  - label: "Icône" 
                    name: "icon"
                    widget: "select"
                    options:
                      - { label: "Tête avec ampoule", value: ico-head-light }
                      - { label: "Tableau", value: icon-chart-ico }
                      - { label: "Écran", value: icon-monitor-ico }
                      - { label: "Téléphone intelligent", value: icon-mobile-ico}
                  - {label: "Visible", name: "visible", widget: "boolean", required: false, default: true}
      - name: "etudes-de-cas"
        label: "Études de cas"
        file: "content/etudes-de-cas/_index.md"
        description: "Texte de votre page études de cas"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text"}
          - {label: "Image de partage", name: "image", widget: "image" , required: false, hint: "La taille recommandée est de 1200px x 630px"}
          - name: top
            label: "Section du haut"
            widget: object
            fields:
              - {label: "Titre", name: "title", widget: "string"}
              - {label: "Image", name: "img", widget: "image", hint: "La taille recommandée est de 1920px par 930px"}
      - name: "a-propos"
        label: "À propos"
        file: "content/singles/iilq.md"
        description: "Texte de votre page IILQ"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text"}
          - {label: "Image de partage", name: "image", widget: "image" , required: false, hint: "La taille recommandée est de 1200px x 630px"}
          - {label: "Slug", name: "slug", widget: "hidden", default: "iilq"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "iilq"}
          - {label: "Texte - Section 1", name: "section1", widget: "text"}
          - {label: "Texte - Section 2", name: "body", widget: "markdown"}
      - name: "clients-et-partenaires"
        label: "Clients & Partenaires"
        file: "content/singles/clients.md"
        description: "Texte de votre page clients"
        fields:
          - {label: "Titre SEO", name: "title", widget: "string"}
          - {label: "Description SEO", name: "description", widget: "text"}
          - {label: "Image de partage", name: "image", widget: "image" , required: false, hint: "La taille recommandée est de 1200px x 630px"}
          - {label: "Slug", name: "slug", widget: "hidden", default: "clients-et-partenaires"}
          - {label: "Layout", name: "layout", widget: "hidden", default: "clients"}
          - {label: "Titre - Partenaires", name: "titre", widget: "string"}
          - name: partenaires
            label: Partenaires
            widget: list
            allow_add: true
            fields:
              - {label: "Nom", name: "nom", widget: "string"}
              - {label: "Image", name: "img", widget: "image" , hint: "La taille minimum devrait être de 400px."}
          - {label: "Titre - Clients", name: "titre2", widget: "string"}
          - name: clients
            label: Clients
            widget: list
            allow_add: true
            fields:
              - {label: "Nom", name: "nom", widget: "string"}
              - {label: "Image", name: "img", widget: "image" , hint: "La taille minimum devrait être de 400px."}
  - name: "autres"
    label: "Autres"
    editor:
      preview: false
    files:
      - name: "menu"
        label: "Menu"
        file: "data/menu.yml"
        description: "Menu"
        fields:
          - name: links
            label: Liens
            widget: list
            allow_add: true
            fields:
              - {label: "Texte", name: "text", widget: "string"}
              - {label: "Lien interne", name: "link", default: "", required: false, widget: "string", hint: "Si vous voulez aller à https://www.innovationlogistique.com/contact, vous devez entrer seulement 'contact'."}
              - {label: "Lien externe", name: "external", default: "", required: false, widget: "string", hint: "Vous devez mettre le lien complet, incluent le http:// ou https://."}
              - name: submenu
                label: "Sous-menu"
                widget: object
                fields:
                  - {label: "Actif", name: "active", widget: "boolean", required: false, default: false}
                  - {label: "Pages transferts", name: "transfert", widget: "boolean", required: false, default: false, hint: "Si vous cochez cette case, toutes les pages de type 'transfert' vont apparaitre dans le sous-menu, rien d'autre."}
                  - {label: "Pages études de cas", name: "casestudy", widget: "boolean", required: false, default: false, hint: "Si vous cochez cette case, toutes les pages de type 'etudes-de-cas' vont apparaitre dans le sous-menu, rien d'autre."}
                  - name: links
                    label: Liens
                    widget: list
                    allow_add: true
                    fields:
                      - {label: "Texte", name: "text", widget: "string"}
                      - {label: "Lien interne", name: "link", default: "", widget: "string", hint: "Si vous voulez aller à https://www.innovationlogistique.com/contact, vous devez entrer seulement 'contact'."}
            